### ISSUE TITLE
server time is not synchronized to NTP

### ISSUE THREAD

**Issue by ppelleti** [haskell/haskell-wiki-configuration#11]
I noticed that the time on www-origin.haskell.org is running about 11 minutes slow.  This is not a big deal, although it does affect the time stamps of things on the wiki, like the modification time of pages.

on www-origin:

```
Thu Feb 16 19:27:36 UTC 2017
```

and at (more or less) the same moment on my MacBook, which is synchronized to NTP:

```
Thu Feb 16 11:38:51 PST 2017
```

I think the solution is as simple as running `sudo apt-get install ntp` on www-origin.  But especially since www-origin is running other things besides the wiki, I wouldn't want to do this without first getting the okay from @gbaz.

**Comment by ppelleti** [comment]
Or I suppose the `sudo` is unnecessary, since I would log in as `root`.  😃

**Comment by gbaz** [comment]
I'd actually consult @thoughtpolice on this?

**Comment by ppelleti** [comment]
@thoughtpolice, is there any reason I shouldn't install ntp on www-origin?

**Comment by hgolden** [comment]
On the new server, just put into production, the server is synchronized using ntpd.
