### ISSUE TITLE
<haskell> element need top and buttom padding on some page

### ISSUE THREAD

**Issue by wizzup** [haskell/haskell-wiki-configuration#13]
Current haskell code block has no padding/margin. 
![2017-03-04-210010_889x441_scrot](https://cloud.githubusercontent.com/assets/342500/23579339/05f72b48-011e-11e7-8154-12e8b36843f3.png)
I try using firefox devtool to alter style sheet by add padding 
![2017-03-04-210109_481x154_scrot](https://cloud.githubusercontent.com/assets/342500/23579342/08a9bb58-011e-11e7-877a-9c7ad34ed64a.png)
Does it look better?
![2017-03-04-205915_768x480_scrot](https://cloud.githubusercontent.com/assets/342500/23579341/06290596-011e-11e7-9c2b-e3910e0c925b.png)

(screenshot taken from this wiki [page](https://wiki.haskell.org/index.php?title=Monad_Transformers_Explained))

Somehow some other page has no problem, [example](https://wiki.haskell.org/Introduction_to_QuickCheck2)

**Comment by hgolden** [comment]
The latest version of the Hawiki skin, just installed into MediaWiki 1.27.4 LTS, has fixed the display of Haskell code.
