### ISSUE TITLE
broken link at 'Learning Haskell'

### ISSUE THREAD

**Issue by epogrebnyak** [haskell/haskell-wiki-configuration#17]
At [this page](https://wiki.haskell.org/Learning_Haskell) in section 2.9 the link to Tour of Prelude in broken. I suggest this link as replacement:

http://www.cse.chalmers.se/edu/course/TDA555/tourofprelude.html

**Comment by ppelleti** [comment]
Thanks!  You can fix this yourself by editing the wiki.

**Comment by hgolden** [comment]
I have updated the link as provided by epogrebnyak above. Thanks!
