### ISSUE TITLE
Add toronto haskell meetup

### ISSUE THREAD

**Issue by Benjmhart** [haskell/haskell-wiki-configuration#18]
the old toronto haskell user group seems to be defunct.

here is information on the new current toronto haskell user group.

https://www.meetup.com/meetup-group-evRITRtT/events/258082340/

**Comment by ppelleti** [comment]
Thanks, but you can just edit the wiki yourself.

**Comment by hgolden** [comment]
Benjmhart added the meetup to the page. Closing issue.
