### ISSUE TITLE
No favicon shown in browsers

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/haskell-wiki-configuration#22]
Previous documentation about doing favicon: https://github.com/haskell/haskell-wiki-configuration/issues/2

Indeed it is present at https://wiki.haskell.org/wikistatic/favicon.ico.

But it is not handled/shown in browsers.

Tested in:
```shell
$ firefox --version
Mozilla Firefox 66.0

$ chromium --version 
Chromium 73.0.3683.75
```

**Comment by hgolden** [comment]
I just added the favicon. Sorry for overlooking this!

Please keep your suggestions coming. It's nice to have someone paying attention!

**Comment by Anton-Latukha** [comment]
Hey! It is already working!
