### ISSUE TITLE
Extract the code for <Haskell> and <Hask> from the old Localsettings.php into 1 or 2 standalone extensions,

### ISSUE THREAD

**Issue by hgolden** [haskell/haskell-wiki-configuration#30]
1. Extract the code
2. Add extension load(s) for the new extension(s).

**Comment by taezaz** [comment]
@hgolden 
Created a pull request here:
https://github.com/haskell/haskell-wiki-configuration/pull/38

**Comment by hgolden** [comment]
Closed by @taezaz in #38
