### ISSUE TITLE
Error Occurs When Pressing the Edit Button

### ISSUE THREAD

**Issue by nattybear** [haskell/haskell-wiki-configuration#39]
When I press the `edit` button, the error occurs like below:

> Error contacting the
> Parsoid/RESTBase server (HTTP 400)

And there are two buttons:
* Cancel
* Try again

However, I can proceed with pressing the `Cancel` button.

**Comment by hgolden** [comment]
@nattybear, Thank you for reporting the problem.

The error is due to a misconfiguration of the Visual Editor. I have disabled the Visual Editor until I can correct the configuration.

**Comment by chreekat** [comment]
I'm going to close this bug report in favor of a new feature request to enable the visual editor: #54 :)
