### ISSUE TITLE
Warning message appears

### ISSUE THREAD

**Issue by nattybear** [haskell/haskell-wiki-configuration#41]
When I try to edit [this page](https://wiki.haskell.org/Ko/Haskell), the warning message appears like below:

> Warning: preg_match(): Unknown modifier 'o' in /usr/share/mediawiki/includes/editpage/SpamChecker.php on line 59

However, I can still make edits.

**Comment by hgolden** [comment]
nattybear: This code was recently added in version 1.35. It doesn't work properly, so I have disabled it. Please let me know if you still get error messages about this.

**Comment by nattybear** [comment]
Now the warning message no longer appears.
