### ISSUE TITLE
Post November 2024 downtime issues list

### ISSUE THREAD

**Issue by axman6** [haskell/haskell-wiki-configuration#44]
Making a new issue to track problems occurring after the Nov 2024 downtime now the OS issues have been resolved. Ops please feel free to rename and edit to hour heart's desire.

**Comment by axman6** [comment]
Homepage lacks all styling and images
<img width="2032" alt="Screenshot 2024-11-15 at 12 52 27" src="https://github.com/user-attachments/assets/789951fe-167e-406c-b2dd-abeacdf97eec">

**Comment by axman6** [comment]
Wiki pages have some styling, and no 404's but appear to be lacking a theme and show `templatestyle` tags.
<img width="2032" alt="Screenshot 2024-11-15 at 12 52 48" src="https://github.com/user-attachments/assets/d8b3f49f-e80c-434d-bdbd-50b74e7b3357">

**Comment by axman6** [comment]
MathJAX appears broken (whit no console messages).
<img width="2032" alt="Screenshot 2024-11-15 at 12 56 10" src="https://github.com/user-attachments/assets/f90fb1b4-9833-40e7-ab58-0852d2581563">

**Comment by willscripted** [comment]
The typeclassopedia pdf appears to not redirect properly, or that file no longer exists in the wiki.

![image](https://github.com/user-attachments/assets/59f0283b-9feb-4e70-a959-27770cd69492)

![image](https://github.com/user-attachments/assets/cfe40be0-db91-4b0e-b19a-81f582fe2cc1)

**Comment by hgolden** [comment]
> The typeclassopedia pdf appears to not redirect properly, or that file no longer exists in the wiki.

@willscripted, I'll take a look at the configuration. It's probably that the upload directory isn't where the configuration says it should be.

**Comment by chreekat** [comment]
Thanks for this list!

I think it's best, however, to create individual tickets out of the individual problems.

Also, we'll need links to individual pages that are broken; screenshots aren't super useful.

I'll help out with this but I'm out of time right now.

**Comment by willscripted** [comment]
> Also, we'll need links to individual pages that are broken; screenshots aren't super useful

Was just kicking myself reading my own comment for not including a link :joy: 

Totally agreed re: individual issues. Would be helpful to see tl;dr's on individual stuffs. Sometimes folks have direct specific experince with things like mathjax and if they have super simple easy answers, it's easier to just chime in on a single thread

**Comment by chreekat** [comment]
MathJax has been fixed at least (not by me)

**Comment by chreekat** [comment]
1. "Homepage lacks all styling" -- resolved
2. "wiki pages show templatestyles tag" -- https://wiki.haskell.org/index.php?title=Haskell
3. "Mathjax appears broken" -- resolved
4. "typeclassopedia pdf link is broken" -- https://wiki.haskell.org/index.php?title=Wikiupload/e/e9/Typeclassopedia.pdf (which is doubly broken -- will open an issue and explain)

I'll open issues for 2 and 4.

**Comment by axman6** [comment]
Looks like all unresolved issues here have tickets, so closing this. Thanks for everyone working to fix things!
