### ISSUE TITLE
Typeclassopedia PDF download link is broken

### ISSUE THREAD

**Issue by chreekat** [haskell/haskell-wiki-configuration#48]
The link as cached by DuckDuckGo: https://www.haskell.org/wikiupload/e/e9/Typeclassopedia.pdf
What the link is redirected to: https://wiki.haskell.org/index.php?title=Wikiupload/e/e9/Typeclassopedia.pdf

![image](https://github.com/user-attachments/assets/2c1d5a9d-be84-4f9e-9dcd-25ca85ee1f76)

There is at least one known change needed, and 2 possible others:

1. The wiki doesn't know that /wikiupload is the expected upload path. `$wgUploadPath` should change.
2. nginx might need a coordinated change
3. ~~The uploads like Typeclassopedia need to actually exist on the new server~~ confirmed ok

**Comment by chreekat** [comment]
The file exists: https://wiki.haskell.org/images/e/e9/Typeclassopedia.pdf

**Comment by hgolden** [comment]
I suggest reverting to the prior article naming URL scheme which will correct the broken links.

**Comment by chreekat** [comment]
Great, that's what my latest PR will do. :) But it depends on the flake PR
that precedes it. Do you want to merge that one, so this repo can be the
canonical configuration location again?

**Comment by hgolden** [comment]
Bryan, I think it's fine to merge the flake PR.

**Comment by chreekat** [comment]
Ok! One of you maintainers will have to do it, though. :) Or you can add me as a maintainer, if you like.

**Comment by hgolden** [comment]
gbaz is the only maintainer atm.

**Comment by chreekat** [comment]
Fixed now, although the code hasn't been merged to this repo yet.

**Comment by chreekat** [comment]
Now the code is merged. :)
