### ISSUE TITLE
Favicon is missing

### ISSUE THREAD

**Issue by chreekat** [haskell/haskell-wiki-configuration#52]
| Q | A |
|--------|--------|
| Test page | https://wiki.haskell.org/index.php?title=Haskell |
| Attempted favicon url |  https://wiki.haskell.org/index.php?title=Favicon.ico |
| href as generated in the source | /favicon.ico | 

## Cause

The cause is that `$wgFavicon` is not set, and the default value is `/favicon.ico`. Since we've enabled short urls (and because that file doesn't exist?), it is interpreted as an article title, and the "article" doesn't exist.

![image](https://github.com/user-attachments/assets/1cfb10f9-3835-4139-84ea-f9a1265b16e3)

### Build /wikistatic

The old site had a `/wikistatic` route, and `$wgFavicon` was set to `/wikistatic/favicon.ico`.

Do we need the rest of the /wikistatic machinery? If so, we should replicate it.

### Plop the favicon.ico in the right spot

Maybe there's already somewhere to put it that it'll get picked up?

**Comment by hgolden** [comment]
The old site's configuration worked. I suggest replicating it.

**Comment by chreekat** [comment]
The favicon is back!
