### ISSUE TITLE
Wiki theme

### ISSUE THREAD

**Issue by ghost** [haskell/haskell-wiki-configuration#9]
The Haskell wiki could really benefit from a nicer theme, better syntax highlighting, etc. An example of a good wiki page to be inspired from would be https://wiki.gentoo.org/wiki/Git

**Comment by ppelleti** [comment]
Thanks for the feedback!

Theme-wise, we ought to be able to use any MediaWiki theme.  Currently, there are two installed:

* HaWiki - this is a custom theme for the Haskell Wiki, and is the default theme
* MonoBook - this is a theme that comes with MediaWiki, although I've discovered in #5 that bad things happen if I select it, so you might want to avoid trying it out until we fix that

I'd be open to installing more themes, if there's a MediaWIki theme you'd like to recommend.  Or, if you'd like to try improving the HaWiki theme, it's available on GitHub as [ppelleti/hawiki][1].

Regarding syntax highlighting, we're looking at that in #6.  The short-term plan is to upgrade GeSHi, and the longer-term plan is to upgrade to Pygments, once we feel comfortable upgrading our MediaWiki installation.

[1]: https://github.com/ppelleti/hawiki

**Comment by hgolden** [comment]
The new version of Hawiki is based on the Vector skin from MediaWiki 1.27.4 LTS. Please take a look and let us know if you think we need to improve anything else.

**Comment by hgolden** [comment]
Default wiki theme switched to vanilla Vector as part of upgrade to 1.35 LTS.
